package addgen

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/arianlopezc/Trabuco/internal/config"
	"github.com/arianlopezc/Trabuco/internal/utils"
)

// EndpointOpts is the input contract for `trabuco add endpoint`.
type EndpointOpts struct {
	Name string // PascalCase resource name; final controller is {Name}Controller
	Type string // "plain" (default) or "crud" — crud emits 5 method stubs
	Path string // override the auto-derived URL path (default: /api/{plural-lower-snake})
}

const (
	EndpointTypePlain = "plain"
	EndpointTypeCRUD  = "crud"
)

// GenerateEndpoint emits API/.../controller/{Name}Controller.java —
// either an empty controller skeleton (Type=plain) or a full CRUD
// scaffold (Type=crud) wired to a Shared service if one matches.
func GenerateEndpoint(ctx *Context, opts EndpointOpts) (*Result, error) {
	name := strings.TrimSpace(opts.Name)
	if name == "" {
		return nil, fmt.Errorf("endpoint name is required (positional argument)")
	}
	if !isValidJavaIdentifier(name) || !isUpperFirst(name) {
		return nil, fmt.Errorf("endpoint name %q must be a PascalCase Java identifier", name)
	}
	if !ctx.HasModule(config.ModuleAPI) {
		return nil, fmt.Errorf("project does not have the API module — controllers live there")
	}
	if opts.Type == "" {
		opts.Type = EndpointTypePlain
	}
	switch opts.Type {
	case EndpointTypePlain, EndpointTypeCRUD:
	default:
		return nil, fmt.Errorf("--type must be plain or crud (got %q)", opts.Type)
	}
	path := opts.Path
	if path == "" {
		path = "/api/" + utils.PluralLowerSnake(name)
	}
	if !strings.HasPrefix(path, "/") {
		path = "/" + path
	}

	rel := filepath.Join(ctx.JavaSrcMain(config.ModuleAPI, "controller"), name+"Controller.java")
	result := &Result{}
	if err := ctx.emitFile(rel, renderEndpoint(ctx, name, path, opts.Type), result); err != nil {
		return nil, err
	}

	result.NextSteps = []string{
		fmt.Sprintf("Add request/response DTOs (e.g. %sRequest, %sResponse) under Model/.../dto if not already present.", name, name),
		"Replace the UnsupportedOperationException stubs with calls into your service layer.",
	}
	if opts.Type == EndpointTypeCRUD {
		result.NextSteps = append(result.NextSteps,
			"Add @PreAuthorize annotations once auth is enabled (trabuco.auth.enabled=true).",
			"Add Bean Validation (@Valid, @NotBlank, @Size) on request bodies.",
		)
	}
	return result, nil
}

func renderEndpoint(ctx *Context, name, path, kind string) string {
	pkg := ctx.JavaPackage(config.ModuleAPI, "controller")
	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	b.WriteString("import org.springframework.http.ResponseEntity;\n")
	b.WriteString("import org.springframework.web.bind.annotation.RequestMapping;\n")
	b.WriteString("import org.springframework.web.bind.annotation.RestController;\n")
	if kind == EndpointTypeCRUD {
		b.WriteString("import org.springframework.web.bind.annotation.DeleteMapping;\n")
		b.WriteString("import org.springframework.web.bind.annotation.GetMapping;\n")
		b.WriteString("import org.springframework.web.bind.annotation.PathVariable;\n")
		b.WriteString("import org.springframework.web.bind.annotation.PostMapping;\n")
		b.WriteString("import org.springframework.web.bind.annotation.PutMapping;\n")
		b.WriteString("import org.springframework.web.bind.annotation.RequestBody;\n")
	}
	b.WriteString("\n")
	b.WriteString("/**\n")
	fmt.Fprintf(&b, " * %sController. Generated by `trabuco add endpoint`.\n", name)
	b.WriteString(" *\n")
	b.WriteString(" * <p>Inject your services via the constructor. Use ResponseEntity\n")
	b.WriteString(" * to control status codes; throw on errors and let GlobalExceptionHandler\n")
	b.WriteString(" * convert to RFC 7807 ProblemDetail.\n")
	b.WriteString(" */\n")
	b.WriteString("@RestController\n")
	fmt.Fprintf(&b, "@RequestMapping(\"%s\")\n", path)
	fmt.Fprintf(&b, "public class %sController {\n\n", name)
	fmt.Fprintf(&b, "  public %sController() {\n", name)
	b.WriteString("    // Inject services via constructor when you add them.\n")
	b.WriteString("  }\n\n")

	if kind == EndpointTypeCRUD {
		b.WriteString("  @PostMapping\n")
		b.WriteString("  public ResponseEntity<Object> create(@RequestBody Object request) {\n")
		b.WriteString("    throw new UnsupportedOperationException(\"create not implemented\");\n")
		b.WriteString("  }\n\n")

		b.WriteString("  @GetMapping(\"/{id}\")\n")
		b.WriteString("  public ResponseEntity<Object> getById(@PathVariable String id) {\n")
		b.WriteString("    throw new UnsupportedOperationException(\"getById not implemented\");\n")
		b.WriteString("  }\n\n")

		b.WriteString("  @GetMapping\n")
		b.WriteString("  public ResponseEntity<Object> list() {\n")
		b.WriteString("    throw new UnsupportedOperationException(\"list not implemented\");\n")
		b.WriteString("  }\n\n")

		b.WriteString("  @PutMapping(\"/{id}\")\n")
		b.WriteString("  public ResponseEntity<Object> update(@PathVariable String id, @RequestBody Object request) {\n")
		b.WriteString("    throw new UnsupportedOperationException(\"update not implemented\");\n")
		b.WriteString("  }\n\n")

		b.WriteString("  @DeleteMapping(\"/{id}\")\n")
		b.WriteString("  public ResponseEntity<Void> delete(@PathVariable String id) {\n")
		b.WriteString("    throw new UnsupportedOperationException(\"delete not implemented\");\n")
		b.WriteString("  }\n")
	}
	b.WriteString("}\n")
	return b.String()
}
