package addgen

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/arianlopezc/Trabuco/internal/config"
)

// generateMongoEntity emits the three-file Mongo entity bundle:
// interface, document, document repository. No migration step
// (Mongo is schemaless; index creation is left to the agent or to
// runtime via @Indexed).
func generateMongoEntity(ctx *Context, opts EntityOpts, fields []Field) (*Result, error) {
	name := opts.Name
	collection := resolveTableName(name, opts.TableName)
	result := &Result{}

	entityRel := filepath.Join(ctx.JavaSrcMain(config.ModuleModel, "entities"), name+".java")
	if err := ctx.emitFile(entityRel, renderMongoEntityInterface(ctx, name, fields), result); err != nil {
		return nil, err
	}

	docRel := filepath.Join(ctx.JavaSrcMain(config.ModuleModel, "entities"), name+"Document.java")
	if err := ctx.emitFile(docRel, renderMongoEntityDocument(ctx, name, collection, fields), result); err != nil {
		return nil, err
	}

	repoRel := filepath.Join(ctx.JavaSrcMain(config.ModuleNoSQLDatastore, "repository"), name+"DocumentRepository.java")
	if err := ctx.emitFile(repoRel, renderMongoRepository(ctx, name), result); err != nil {
		return nil, err
	}

	seenEnums := map[string]bool{}
	for _, f := range fields {
		if f.Type != FTEnum || seenEnums[f.EnumName] {
			continue
		}
		seenEnums[f.EnumName] = true
		if err := ctx.emitEnumIfMissing(f.EnumName, result); err != nil {
			return nil, err
		}
	}

	result.NextSteps = []string{
		fmt.Sprintf("Edit %s if you need findBy* finders or aggregation pipelines.", repoRel),
		fmt.Sprintf("Add @Indexed annotations to %sDocument fields you query frequently — Spring Data MongoDB creates them at boot.", name),
		fmt.Sprintf("Wire %s into your service layer via the Immutable builder: %s.builder()....build().", name, entityImmutable(name)),
	}
	if len(seenEnums) > 0 {
		result.NextSteps = append(result.NextSteps,
			"Replace the PLACEHOLDER_VALUE constant in each generated enum with your actual states.")
	}
	return result, nil
}

func renderMongoEntityInterface(ctx *Context, name string, fields []Field) string {
	pkg := ctx.JavaPackage(config.ModuleModel, "entities")
	imports := uniqueImports(fields,
		"com.fasterxml.jackson.databind.annotation.JsonDeserialize",
		"com.fasterxml.jackson.databind.annotation.JsonSerialize",
		"jakarta.annotation.Nullable",
		"org.immutables.value.Value",
		ctx.GroupID+".model.ImmutableStyle",
	)

	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	for _, imp := range imports {
		fmt.Fprintf(&b, "import %s;\n", imp)
	}
	b.WriteString("\n")
	b.WriteString("/**\n")
	fmt.Fprintf(&b, " * %s entity for SERVICE LAYER business logic (MongoDB flavor).\n", name)
	b.WriteString(" *\n")
	fmt.Fprintf(&b, " * <p>Use %s.builder() to create instances. %sDocument is the\n", entityImmutable(name), name)
	b.WriteString(" * Spring Data MongoDB persistence model.\n")
	b.WriteString(" *\n")
	b.WriteString(" * <p>Generated by `trabuco add entity`.\n")
	b.WriteString(" */\n")
	b.WriteString("@Value.Immutable\n")
	b.WriteString("@ImmutableStyle\n")
	fmt.Fprintf(&b, "@JsonSerialize(as = %s.class)\n", entityImmutable(name))
	fmt.Fprintf(&b, "@JsonDeserialize(as = %s.class)\n", entityImmutable(name))
	fmt.Fprintf(&b, "public interface %s {\n", name)
	b.WriteString("  /** Mongo document identifier (assigned on insert). */\n")
	b.WriteString("  @Nullable\n")
	b.WriteString("  String documentId();\n")
	for _, f := range fields {
		b.WriteString("\n")
		if f.Nullable {
			b.WriteString("  @Nullable\n")
		}
		fmt.Fprintf(&b, "  %s %s();\n", f.JavaType(), f.Name)
	}
	b.WriteString("}\n")
	return b.String()
}

func renderMongoEntityDocument(ctx *Context, name, collection string, fields []Field) string {
	pkg := ctx.JavaPackage(config.ModuleModel, "entities")
	imports := uniqueImports(fields,
		"jakarta.annotation.Nullable",
		"org.springframework.data.annotation.Id",
		"org.springframework.data.mongodb.core.mapping.Document",
	)

	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	for _, imp := range imports {
		fmt.Fprintf(&b, "import %s;\n", imp)
	}
	b.WriteString("\n")
	b.WriteString("/**\n")
	fmt.Fprintf(&b, " * %sDocument for MongoDB persistence. Use the %s interface for business logic.\n", name, name)
	b.WriteString(" *\n")
	b.WriteString(" * <p>Generated by `trabuco add entity`.\n")
	b.WriteString(" */\n")
	fmt.Fprintf(&b, "@Document(collection = \"%s\")\n", collection)
	fmt.Fprintf(&b, "public record %sDocument(\n", name)
	b.WriteString("  @Id @Nullable String documentId")
	for _, f := range fields {
		b.WriteString(",\n")
		b.WriteString("  ")
		if f.Nullable {
			b.WriteString("@Nullable ")
		}
		fmt.Fprintf(&b, "%s %s", f.JavaType(), f.Name)
	}
	b.WriteString("\n) {\n}\n")
	return b.String()
}

func renderMongoRepository(ctx *Context, name string) string {
	pkg := ctx.JavaPackage(config.ModuleNoSQLDatastore, "repository")
	entityPkg := ctx.JavaPackage(config.ModuleModel, "entities")
	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	fmt.Fprintf(&b, "import %s.%sDocument;\n", entityPkg, name)
	b.WriteString("import org.springframework.data.mongodb.repository.MongoRepository;\n")
	b.WriteString("import org.springframework.stereotype.Repository;\n\n")
	b.WriteString("/**\n")
	fmt.Fprintf(&b, " * Spring Data MongoDB repository for %sDocument.\n", name)
	b.WriteString(" *\n")
	b.WriteString(" * <p>MongoRepository extends CrudRepository — same findById/save/deleteById\n")
	b.WriteString(" * surface as the SQL flavor, plus aggregation helpers.\n")
	b.WriteString(" *\n")
	b.WriteString(" * <p>Generated by `trabuco add entity`.\n")
	b.WriteString(" */\n")
	b.WriteString("@Repository\n")
	fmt.Fprintf(&b, "public interface %sDocumentRepository extends MongoRepository<%sDocument, String> {\n", name, name)
	b.WriteString("}\n")
	return b.String()
}
