package addgen

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/arianlopezc/Trabuco/internal/config"
)

// generateSQLEntity emits the four-file SQL entity bundle (interface,
// record, repository, migration) plus any enum stubs.
func generateSQLEntity(ctx *Context, opts EntityOpts, fields []Field) (*Result, error) {
	name := opts.Name
	tableName := resolveTableName(name, opts.TableName)
	result := &Result{}

	entityRel := filepath.Join(ctx.JavaSrcMain(config.ModuleModel, "entities"), name+".java")
	if err := ctx.emitFile(entityRel, renderSQLEntityInterface(ctx, name, fields), result); err != nil {
		return nil, err
	}

	recordRel := filepath.Join(ctx.JavaSrcMain(config.ModuleModel, "entities"), name+"Record.java")
	if err := ctx.emitFile(recordRel, renderSQLEntityRecord(ctx, name, tableName, fields), result); err != nil {
		return nil, err
	}

	repoRel := filepath.Join(ctx.JavaSrcMain(config.ModuleSQLDatastore, "repository"), name+"Repository.java")
	if err := ctx.emitFile(repoRel, renderSQLRepository(ctx, name), result); err != nil {
		return nil, err
	}

	migrationDir := ctx.ResourcesMain(config.ModuleSQLDatastore, filepath.Join("db", "migration"))
	version, err := nextMigrationVersion(filepath.Join(ctx.ProjectPath, migrationDir))
	if err != nil {
		return nil, err
	}
	migrationRel := filepath.Join(migrationDir, fmt.Sprintf("V%d__create_%s.sql", version, tableName))
	if err := ctx.emitFile(migrationRel, renderSQLMigration(version, tableName, ctx.Database, fields), result); err != nil {
		return nil, err
	}

	seenEnums := map[string]bool{}
	for _, f := range fields {
		if f.Type != FTEnum || seenEnums[f.EnumName] {
			continue
		}
		seenEnums[f.EnumName] = true
		if err := ctx.emitEnumIfMissing(f.EnumName, result); err != nil {
			return nil, err
		}
	}

	result.NextSteps = []string{
		fmt.Sprintf("Edit %s if you need additional repository queries (findBy*, paged reads, batch updates).", repoRel),
		fmt.Sprintf("Edit %s to add indexes, FK columns, or default values your domain needs.", migrationRel),
		fmt.Sprintf("Wire %s into your service layer with a builder: %s.builder()....build().", name, entityImmutable(name)),
	}
	if len(seenEnums) > 0 {
		result.NextSteps = append(result.NextSteps,
			"Replace the PLACEHOLDER_VALUE constant in each generated enum with your actual states.")
	}
	return result, nil
}

// entityImmutable returns the canonical Immutables-generated builder
// class name (e.g. "Order" → "ImmutableOrder").
func entityImmutable(name string) string {
	return "Immutable" + name
}

// renderSQLEntityInterface emits the Immutables service-layer
// interface — Long id() for the SQL flavor, then user fields with
// @Nullable annotations on optional ones.
func renderSQLEntityInterface(ctx *Context, name string, fields []Field) string {
	pkg := ctx.JavaPackage(config.ModuleModel, "entities")
	imports := uniqueImports(fields,
		"com.fasterxml.jackson.databind.annotation.JsonDeserialize",
		"com.fasterxml.jackson.databind.annotation.JsonSerialize",
		"jakarta.annotation.Nullable",
		"org.immutables.value.Value",
		ctx.GroupID+".model.ImmutableStyle",
	)

	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	for _, imp := range imports {
		fmt.Fprintf(&b, "import %s;\n", imp)
	}
	b.WriteString("\n")
	b.WriteString("/**\n")
	fmt.Fprintf(&b, " * %s entity for SERVICE LAYER business logic.\n", name)
	b.WriteString(" *\n")
	fmt.Fprintf(&b, " * <p>Always use %s.builder() to create instances.\n", entityImmutable(name))
	fmt.Fprintf(&b, " * %sRecord is used for SQL database persistence.\n", name)
	b.WriteString(" *\n")
	b.WriteString(" * <p>Generated by `trabuco add entity`.\n")
	b.WriteString(" */\n")
	b.WriteString("@Value.Immutable\n")
	b.WriteString("@ImmutableStyle\n")
	fmt.Fprintf(&b, "@JsonSerialize(as = %s.class)\n", entityImmutable(name))
	fmt.Fprintf(&b, "@JsonDeserialize(as = %s.class)\n", entityImmutable(name))
	fmt.Fprintf(&b, "public interface %s {\n", name)
	b.WriteString("  /** SQL unique identifier (auto-generated). */\n")
	b.WriteString("  @Nullable\n")
	b.WriteString("  Long id();\n")
	for _, f := range fields {
		b.WriteString("\n")
		if f.Nullable {
			b.WriteString("  @Nullable\n")
		}
		fmt.Fprintf(&b, "  %s %s();\n", f.JavaType(), f.Name)
	}
	b.WriteString("}\n")
	return b.String()
}

// renderSQLEntityRecord emits the Spring Data JDBC record class.
// The @Table annotation pins the table name; @Id marks the auto-PK.
// Fields are listed in user order after id, mirroring the migration
// column order so visual diffing stays sane.
func renderSQLEntityRecord(ctx *Context, name, tableName string, fields []Field) string {
	pkg := ctx.JavaPackage(config.ModuleModel, "entities")
	imports := uniqueImports(fields,
		"jakarta.annotation.Nullable",
		"org.springframework.data.annotation.Id",
		"org.springframework.data.relational.core.mapping.Table",
	)

	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	for _, imp := range imports {
		fmt.Fprintf(&b, "import %s;\n", imp)
	}
	b.WriteString("\n")
	b.WriteString("/**\n")
	fmt.Fprintf(&b, " * %sRecord for DATABASE PERSISTENCE.\n", name)
	b.WriteString(" * Used by Spring Data JDBC repositories. For business logic, use the\n")
	fmt.Fprintf(&b, " * %s interface instead.\n", name)
	b.WriteString(" *\n")
	b.WriteString(" * <p>Generated by `trabuco add entity`.\n")
	b.WriteString(" */\n")
	fmt.Fprintf(&b, "@Table(\"%s\")\n", tableName)
	fmt.Fprintf(&b, "public record %sRecord(\n", name)
	b.WriteString("  @Id @Nullable Long id")
	for _, f := range fields {
		b.WriteString(",\n")
		b.WriteString("  ")
		if f.Nullable {
			b.WriteString("@Nullable ")
		}
		fmt.Fprintf(&b, "%s %s", f.JavaType(), f.Name)
	}
	b.WriteString("\n) {\n}\n")
	return b.String()
}

// renderSQLRepository emits a minimal Spring Data JDBC repository.
// CrudRepository<Record, Long> gets you findById, findAll, save,
// deleteById out of the box. The agent adds custom @Query methods as
// the domain demands.
func renderSQLRepository(ctx *Context, name string) string {
	pkg := ctx.JavaPackage(config.ModuleSQLDatastore, "repository")
	entityPkg := ctx.JavaPackage(config.ModuleModel, "entities")
	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	fmt.Fprintf(&b, "import %s.%sRecord;\n", entityPkg, name)
	b.WriteString("import org.springframework.data.repository.CrudRepository;\n")
	b.WriteString("import org.springframework.stereotype.Repository;\n\n")
	b.WriteString("/**\n")
	fmt.Fprintf(&b, " * Spring Data JDBC repository for %sRecord.\n", name)
	b.WriteString(" *\n")
	b.WriteString(" * <p>CrudRepository gives you findById/findAll/save/deleteById for free.\n")
	b.WriteString(" * Add @Query methods here for custom finders, batch reads (IN), keyset\n")
	b.WriteString(" * pagination, and bounded bulk UPDATE patterns. See JAVA_CODE_QUALITY.md §5.5.\n")
	b.WriteString(" *\n")
	b.WriteString(" * <p>Generated by `trabuco add entity`.\n")
	b.WriteString(" */\n")
	b.WriteString("@Repository\n")
	fmt.Fprintf(&b, "public interface %sRepository extends CrudRepository<%sRecord, Long> {\n", name, name)
	b.WriteString("}\n")
	return b.String()
}

// renderSQLMigration emits the CREATE TABLE DDL for an entity.
// Database-aware: BIGSERIAL/BIGINT AUTO_INCREMENT, NUMERIC vs DECIMAL,
// JSONB vs JSON, etc. Uses IF NOT EXISTS so manual bootstrap paths
// don't fatally fail (matches the V1__baseline.sql pattern).
func renderSQLMigration(version int, tableName, database string, fields []Field) string {
	var b strings.Builder
	fmt.Fprintf(&b, "-- V%d__create_%s.sql\n", version, tableName)
	b.WriteString("-- Generated by `trabuco add entity`. Edit before applying to add\n")
	b.WriteString("-- indexes, FK columns, default values, or constraints your domain needs.\n\n")

	fmt.Fprintf(&b, "CREATE TABLE IF NOT EXISTS %s (\n", tableName)
	fmt.Fprintf(&b, "    id %s,\n", autoIDColumn(database))
	for i, f := range fields {
		nullClause := " NOT NULL"
		if f.Nullable {
			nullClause = ""
		}
		comma := ","
		if i == len(fields)-1 {
			comma = ""
		}
		fmt.Fprintf(&b, "    %s %s%s%s\n", f.ColumnName(), f.SQLType(database), nullClause, comma)
	}
	b.WriteString(");\n")
	return b.String()
}

// autoIDColumn returns the database-flavored auto-PK column DDL.
//
//	postgresql → "BIGSERIAL PRIMARY KEY"
//	mysql      → "BIGINT AUTO_INCREMENT PRIMARY KEY"
//	other      → "BIGINT PRIMARY KEY" (caller fills in default)
func autoIDColumn(database string) string {
	switch database {
	case config.DatabasePostgreSQL:
		return "BIGSERIAL PRIMARY KEY"
	case config.DatabaseMySQL:
		return "BIGINT AUTO_INCREMENT PRIMARY KEY"
	}
	return "BIGINT PRIMARY KEY"
}
