package addgen

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/arianlopezc/Trabuco/internal/config"
)

// EventOpts is the input contract for `trabuco add event`.
type EventOpts struct {
	Name   string // PascalCase event class name
	Fields string // ParseFields-format spec
}

// GenerateEvent emits Model/.../events/{Name}.java — a Java record
// representing a domain event. Unlike entities, events have no
// repository/migration/document — they're transport DTOs.
//
// The class is intentionally NOT added to any sealed permits clause;
// the agent owns wiring it into existing event hierarchies (the CLI
// is addition-only — no edits).
func GenerateEvent(ctx *Context, opts EventOpts) (*Result, error) {
	name := strings.TrimSpace(opts.Name)
	if name == "" {
		return nil, fmt.Errorf("event name is required (positional argument)")
	}
	if !isValidJavaIdentifier(name) || !isUpperFirst(name) {
		return nil, fmt.Errorf("event name %q must be a PascalCase Java identifier", name)
	}
	if !ctx.HasModule(config.ModuleModel) {
		return nil, fmt.Errorf("project does not have the Model module — events live there")
	}

	fields, err := ParseFields(opts.Fields)
	if err != nil {
		return nil, err
	}

	rel := filepath.Join(ctx.JavaSrcMain(config.ModuleModel, "events"), name+".java")
	result := &Result{}
	if err := ctx.emitFile(rel, renderEventRecord(ctx, name, fields), result); err != nil {
		return nil, err
	}

	seenEnums := map[string]bool{}
	for _, f := range fields {
		if f.Type != FTEnum || seenEnums[f.EnumName] {
			continue
		}
		seenEnums[f.EnumName] = true
		if err := ctx.emitEnumIfMissing(f.EnumName, result); err != nil {
			return nil, err
		}
	}

	result.NextSteps = []string{
		fmt.Sprintf("If %s is part of a sealed event hierarchy, add it to the parent's `permits` clause.", name),
		"Add @JsonProperty annotations on fields if you need wire-format stability across services.",
		"Wire the event into your event listener / publisher — the CLI does not edit existing files.",
	}
	return result, nil
}

func renderEventRecord(ctx *Context, name string, fields []Field) string {
	pkg := ctx.JavaPackage(config.ModuleModel, "events")
	imports := uniqueImports(fields,
		"jakarta.annotation.Nullable",
		"jakarta.validation.constraints.NotNull",
	)

	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	for _, imp := range imports {
		fmt.Fprintf(&b, "import %s;\n", imp)
	}
	b.WriteString("\n")
	b.WriteString("/**\n")
	fmt.Fprintf(&b, " * %s domain event. Generated by `trabuco add event`.\n", name)
	b.WriteString(" *\n")
	b.WriteString(" * <p>Records are immutable by construction — pass them across module\n")
	b.WriteString(" * boundaries (events listener → service, message broker payload, etc.)\n")
	b.WriteString(" * without defensive copies.\n")
	b.WriteString(" */\n")
	fmt.Fprintf(&b, "public record %s(\n", name)
	for i, f := range fields {
		if i > 0 {
			b.WriteString(",\n")
		}
		b.WriteString("  ")
		if f.Nullable {
			b.WriteString("@Nullable ")
		} else {
			b.WriteString("@NotNull ")
		}
		fmt.Fprintf(&b, "%s %s", f.JavaType(), f.Name)
	}
	b.WriteString("\n) {\n}\n")
	return b.String()
}
