package addgen

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/arianlopezc/Trabuco/internal/config"
)

// JobOpts is the input contract for `trabuco add job`.
type JobOpts struct {
	Name    string // verb-noun PascalCase, e.g. "ProcessShipment". The CLI does not auto-prefix "Process"; the user controls naming.
	Payload string // ParseFields-format payload spec (e.g. "orderId:string,amount:decimal")
}

// GenerateJob emits the three-file JobRunr job bundle:
//
//   - Model/.../jobs/{Name}JobRequest.java          (record, JobRequest)
//   - Model/.../jobs/{Name}JobRequestHandler.java   (abstract handler, JobRequestHandler<T>)
//   - Worker/.../handler/{Name}JobRequestHandler.java  (concrete @Component)
//
// Mirrors the ProcessPlaceholder convention: the Model side carries
// the request record and a no-op base handler so JobRunr's enqueue-
// time validation finds a concrete class on the classpath; the Worker
// side overrides run() with real logic.
func GenerateJob(ctx *Context, opts JobOpts) (*Result, error) {
	name := strings.TrimSpace(opts.Name)
	if name == "" {
		return nil, fmt.Errorf("job name is required (positional argument)")
	}
	if !isValidJavaIdentifier(name) || !isUpperFirst(name) {
		return nil, fmt.Errorf("job name %q must be a PascalCase Java identifier", name)
	}
	if !ctx.HasModule(config.ModuleModel) {
		return nil, fmt.Errorf("project does not have the Model module — JobRequest types live there")
	}
	if !ctx.HasModule(config.ModuleWorker) {
		return nil, fmt.Errorf("project does not have the Worker module — JobRunr handlers live there")
	}

	fields, err := ParseFields(opts.Payload)
	if err != nil {
		return nil, fmt.Errorf("invalid --payload: %w", err)
	}

	result := &Result{}

	requestRel := filepath.Join(ctx.JavaSrcMain(config.ModuleModel, "jobs"), name+"JobRequest.java")
	if err := ctx.emitFile(requestRel, renderJobRequest(ctx, name, fields), result); err != nil {
		return nil, err
	}

	handlerBaseRel := filepath.Join(ctx.JavaSrcMain(config.ModuleModel, "jobs"), name+"JobRequestHandler.java")
	if err := ctx.emitFile(handlerBaseRel, renderJobHandlerBase(ctx, name), result); err != nil {
		return nil, err
	}

	handlerRel := filepath.Join(ctx.JavaSrcMain(config.ModuleWorker, "handler"), name+"JobRequestHandler.java")
	if err := ctx.emitFile(handlerRel, renderJobHandlerConcrete(ctx, name), result); err != nil {
		return nil, err
	}

	seenEnums := map[string]bool{}
	for _, f := range fields {
		if f.Type != FTEnum || seenEnums[f.EnumName] {
			continue
		}
		seenEnums[f.EnumName] = true
		if err := ctx.emitEnumIfMissing(f.EnumName, result); err != nil {
			return nil, err
		}
	}

	result.NextSteps = []string{
		fmt.Sprintf("Implement %s in the Worker module — replace the TODO body with your business logic.", handlerRel),
		fmt.Sprintf("Enqueue jobs from any module that depends on Model: BackgroundJobRequest.enqueue(new %sJobRequest(...))", name),
		"For recurring schedules, register the job in Worker/.../config/RecurringJobsConfig.java.",
	}
	return result, nil
}

func renderJobRequest(ctx *Context, name string, fields []Field) string {
	pkg := ctx.JavaPackage(config.ModuleModel, "jobs")
	imports := uniqueImports(fields,
		"org.jobrunr.jobs.lambdas.JobRequest",
	)

	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	for _, imp := range imports {
		fmt.Fprintf(&b, "import %s;\n", imp)
	}
	b.WriteString("\n")
	b.WriteString("/**\n")
	fmt.Fprintf(&b, " * Job request for %s. Generated by `trabuco add job`.\n", name)
	b.WriteString(" *\n")
	b.WriteString(" * <p>Enqueue: BackgroundJobRequest.enqueue(new ")
	b.WriteString(name)
	b.WriteString("JobRequest(...));\n")
	b.WriteString(" */\n")
	fmt.Fprintf(&b, "public record %sJobRequest(\n", name)
	for i, f := range fields {
		if i > 0 {
			b.WriteString(",\n")
		}
		fmt.Fprintf(&b, "    %s %s", f.JavaType(), f.Name)
	}
	b.WriteString("\n) implements JobRequest {\n\n")
	b.WriteString("  @Override\n")
	fmt.Fprintf(&b, "  public Class<%sJobRequestHandler> getJobRequestHandler() {\n", name)
	fmt.Fprintf(&b, "    return %sJobRequestHandler.class;\n", name)
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String()
}

func renderJobHandlerBase(ctx *Context, name string) string {
	pkg := ctx.JavaPackage(config.ModuleModel, "jobs")
	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	b.WriteString("import org.jobrunr.jobs.lambdas.JobRequestHandler;\n\n")
	b.WriteString("/**\n")
	fmt.Fprintf(&b, " * Concrete base handler for %sJobRequest.\n", name)
	b.WriteString(" *\n")
	b.WriteString(" * <p>Lives in the Model module so getJobRequestHandler() can reference\n")
	b.WriteString(" * it without a runtime dependency on Worker. The @Component subclass in\n")
	b.WriteString(" * the Worker module overrides run() with real logic.\n")
	b.WriteString(" */\n")
	fmt.Fprintf(&b, "public class %sJobRequestHandler implements JobRequestHandler<%sJobRequest> {\n\n", name, name)
	b.WriteString("  /** No-op default — overridden by the Worker module's @Component subclass. */\n")
	b.WriteString("  @Override\n")
	fmt.Fprintf(&b, "  public void run(%sJobRequest request) {\n", name)
	b.WriteString("    // No-op — overridden in Worker module.\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String()
}

func renderJobHandlerConcrete(ctx *Context, name string) string {
	pkg := ctx.JavaPackage(config.ModuleWorker, "handler")
	jobsPkg := ctx.JavaPackage(config.ModuleModel, "jobs")
	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	fmt.Fprintf(&b, "import %s.%sJobRequest;\n", jobsPkg, name)
	b.WriteString("import org.jobrunr.jobs.annotations.Job;\n")
	b.WriteString("import org.slf4j.Logger;\n")
	b.WriteString("import org.slf4j.LoggerFactory;\n")
	b.WriteString("import org.springframework.stereotype.Component;\n\n")
	b.WriteString("/**\n")
	fmt.Fprintf(&b, " * Concrete handler for %sJobRequest. Generated by `trabuco add job`.\n", name)
	b.WriteString(" *\n")
	b.WriteString(" * <p>Make handlers idempotent — JobRunr retries on failure.\n")
	b.WriteString(" * Inject dependencies via constructor.\n")
	b.WriteString(" */\n")
	b.WriteString("@Component\n")
	fmt.Fprintf(&b, "public class %sJobRequestHandler\n", name)
	fmt.Fprintf(&b, "    extends %s.%sJobRequestHandler {\n\n", jobsPkg, name)
	fmt.Fprintf(&b, "  private static final Logger log = LoggerFactory.getLogger(%sJobRequestHandler.class);\n\n", name)
	b.WriteString("  @Override\n")
	fmt.Fprintf(&b, "  @Job(name = \"%s\")\n", name)
	fmt.Fprintf(&b, "  public void run(%sJobRequest request) {\n", name)
	fmt.Fprintf(&b, "    log.info(\"Running %s with payload: {}\", request);\n", name)
	b.WriteString("    // TODO: replace this with your business logic.\n")
	b.WriteString("    throw new UnsupportedOperationException(\"not implemented\");\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String()
}
