package addgen

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/arianlopezc/Trabuco/internal/config"
)

// ServiceOpts is the input contract for `trabuco add service`.
type ServiceOpts struct {
	Name   string // PascalCase service class name (e.g. "OrderService")
	Entity string // optional entity name; injects {Entity}Repository when set and SQLDatastore present
}

// GenerateService emits Shared/.../service/{Name}.java — a @Service
// class with constructor injection. When Entity is set, the
// constructor wires in the matching repository (SQL or Mongo).
func GenerateService(ctx *Context, opts ServiceOpts) (*Result, error) {
	name := strings.TrimSpace(opts.Name)
	if name == "" {
		return nil, fmt.Errorf("service name is required (positional argument)")
	}
	if !isValidJavaIdentifier(name) || !isUpperFirst(name) {
		return nil, fmt.Errorf("service name %q must be a PascalCase Java identifier", name)
	}
	if !ctx.HasModule(config.ModuleShared) {
		return nil, fmt.Errorf("project does not have the Shared module — services live there")
	}

	rel := filepath.Join(ctx.JavaSrcMain(config.ModuleShared, "service"), name+".java")
	result := &Result{}
	if err := ctx.emitFile(rel, renderService(ctx, name, opts.Entity), result); err != nil {
		return nil, err
	}

	if opts.Entity != "" {
		if !isValidJavaIdentifier(opts.Entity) || !isUpperFirst(opts.Entity) {
			result.Notes = append(result.Notes,
				fmt.Sprintf("--entity=%q is not a PascalCase identifier; the generated import line is likely broken — fix manually.", opts.Entity))
		}
	}

	result.NextSteps = []string{
		fmt.Sprintf("Replace the placeholder method in %s with your real business operations.", rel),
	}
	if opts.Entity != "" {
		result.NextSteps = append(result.NextSteps,
			fmt.Sprintf("Implement CRUD methods that call the injected %s%s.", opts.Entity, repoSuffixForEntity(ctx, opts.Entity)))
	}
	return result, nil
}

// repoSuffixForEntity returns "Repository" for SQL projects and
// "DocumentRepository" for Mongo projects. The entity parameter is
// kept for symmetry with other helpers and to avoid drift if the
// suffix ever becomes entity-dependent. Used in NextSteps text.
func repoSuffixForEntity(ctx *Context, _ string) string {
	if ctx.HasModule(config.ModuleNoSQLDatastore) && !ctx.HasModule(config.ModuleSQLDatastore) {
		return "DocumentRepository"
	}
	return "Repository"
}

func renderService(ctx *Context, name, entity string) string {
	pkg := ctx.JavaPackage(config.ModuleShared, "service")
	var imports []string
	imports = append(imports, "org.springframework.stereotype.Service")

	repoClass := ""
	repoField := ""
	repoImport := ""
	if entity != "" {
		switch {
		case ctx.HasModule(config.ModuleSQLDatastore):
			repoClass = entity + "Repository"
			repoImport = ctx.JavaPackage(config.ModuleSQLDatastore, "repository") + "." + repoClass
			repoField = lowerFirst(entity) + "Repository"
		case ctx.HasModule(config.ModuleNoSQLDatastore):
			repoClass = entity + "DocumentRepository"
			repoImport = ctx.JavaPackage(config.ModuleNoSQLDatastore, "repository") + "." + repoClass
			repoField = lowerFirst(entity) + "DocumentRepository"
		}
	}
	if repoImport != "" {
		imports = append(imports, repoImport)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	for _, imp := range imports {
		fmt.Fprintf(&b, "import %s;\n", imp)
	}
	b.WriteString("\n")
	b.WriteString("/**\n")
	fmt.Fprintf(&b, " * %s — Spring service stub generated by `trabuco add service`.\n", name)
	b.WriteString(" *\n")
	b.WriteString(" * <p>Add business operations as public methods. Use constructor\n")
	b.WriteString(" * injection for all dependencies (no @Autowired field injection).\n")
	b.WriteString(" * Wrap multi-step writes in @Transactional.\n")
	b.WriteString(" */\n")
	b.WriteString("@Service\n")
	fmt.Fprintf(&b, "public class %s {\n\n", name)

	if repoClass != "" {
		fmt.Fprintf(&b, "  private final %s %s;\n\n", repoClass, repoField)
		fmt.Fprintf(&b, "  public %s(%s %s) {\n", name, repoClass, repoField)
		fmt.Fprintf(&b, "    this.%s = %s;\n", repoField, repoField)
		b.WriteString("  }\n\n")
	} else {
		fmt.Fprintf(&b, "  public %s() {\n", name)
		b.WriteString("    // Inject dependencies via constructor when you add them.\n")
		b.WriteString("  }\n\n")
	}

	b.WriteString("  /** Replace with a real operation. */\n")
	b.WriteString("  public void doSomething() {\n")
	b.WriteString("    throw new UnsupportedOperationException(\"not implemented\");\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String()
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	first := s[0]
	if first >= 'A' && first <= 'Z' {
		return string(first+32) + s[1:]
	}
	return s
}
