package addgen

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/arianlopezc/Trabuco/internal/config"
)

// StreamingEndpointOpts is the input contract for
// `trabuco add streaming-endpoint`. AIAgent-only.
type StreamingEndpointOpts struct {
	Name string // PascalCase controller name (e.g. "Conversation" → ConversationStreamController)
	Path string // override the auto-derived URL path
}

// GenerateStreamingEndpoint emits AIAgent/.../protocol/{Name}StreamController.java
// — a Server-Sent Events controller skeleton suitable for LLM token
// streaming or any long-lived request.
func GenerateStreamingEndpoint(ctx *Context, opts StreamingEndpointOpts) (*Result, error) {
	name := strings.TrimSpace(opts.Name)
	if name == "" {
		return nil, fmt.Errorf("streaming-endpoint name is required (positional argument)")
	}
	if !isValidJavaIdentifier(name) || !isUpperFirst(name) {
		return nil, fmt.Errorf("name %q must be a PascalCase Java identifier", name)
	}
	if !ctx.HasModule(config.ModuleAIAgent) {
		return nil, fmt.Errorf("project does not have the AIAgent module — streaming endpoints live there")
	}

	path := opts.Path
	if path == "" {
		path = "/api/agent/stream/" + lowerFirst(name)
	}
	if !strings.HasPrefix(path, "/") {
		path = "/" + path
	}

	rel := filepath.Join(ctx.JavaSrcMain(config.ModuleAIAgent, "protocol"), name+"StreamController.java")
	result := &Result{}
	if err := ctx.emitFile(rel, renderStreamingEndpoint(ctx, name, path), result); err != nil {
		return nil, err
	}

	result.NextSteps = []string{
		fmt.Sprintf("Replace the heartbeat-only loop in %s with real token streaming from your AIAgent.", rel),
		"Wire CallerContext + rate-limit + per-caller slot accounting using the helpers already present in the AIAgent module.",
		"Add @PreAuthorize once auth is enabled — streaming endpoints typically require an authenticated caller.",
	}
	return result, nil
}

func renderStreamingEndpoint(ctx *Context, name, path string) string {
	pkg := ctx.JavaPackage(config.ModuleAIAgent, "protocol")
	var b strings.Builder
	fmt.Fprintf(&b, "package %s;\n\n", pkg)
	b.WriteString("import org.springframework.http.MediaType;\n")
	b.WriteString("import org.springframework.web.bind.annotation.GetMapping;\n")
	b.WriteString("import org.springframework.web.bind.annotation.PathVariable;\n")
	b.WriteString("import org.springframework.web.bind.annotation.RestController;\n")
	b.WriteString("import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;\n\n")
	b.WriteString("import java.io.IOException;\n\n")
	b.WriteString("/**\n")
	fmt.Fprintf(&b, " * %sStreamController — SSE streaming endpoint generated by\n", name)
	b.WriteString(" * `trabuco add streaming-endpoint`. Replace the placeholder loop with\n")
	b.WriteString(" * real token streaming from your AIAgent layer.\n")
	b.WriteString(" *\n")
	b.WriteString(" * <p>The AIAgent module ships rate-limit + per-caller slot accounting\n")
	b.WriteString(" * helpers (CallerContext, RateLimiter, slot acquisition). Wire them in\n")
	b.WriteString(" * around the emitter to enforce per-tenant limits.\n")
	b.WriteString(" */\n")
	b.WriteString("@RestController\n")
	fmt.Fprintf(&b, "public class %sStreamController {\n\n", name)
	b.WriteString("  private static final long EMITTER_TIMEOUT_MS = 5L * 60_000L; // 5m default\n\n")
	fmt.Fprintf(&b, "  @GetMapping(value = \"%s/{id}\", produces = MediaType.TEXT_EVENT_STREAM_VALUE)\n", path)
	b.WriteString("  public SseEmitter stream(@PathVariable String id) {\n")
	b.WriteString("    SseEmitter emitter = new SseEmitter(EMITTER_TIMEOUT_MS);\n")
	b.WriteString("    Thread.startVirtualThread(() -> {\n")
	b.WriteString("      try {\n")
	b.WriteString("        // TODO: replace with real token streaming.\n")
	b.WriteString("        emitter.send(SseEmitter.event().name(\"hello\").data(\"streaming for \" + id));\n")
	b.WriteString("        emitter.complete();\n")
	b.WriteString("      } catch (IOException e) {\n")
	b.WriteString("        emitter.completeWithError(e);\n")
	b.WriteString("      }\n")
	b.WriteString("    });\n")
	b.WriteString("    return emitter;\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String()
}
