package sync

import "strings"

// Trabuco-managed marker comments. Files that contain a block delimited
// by these markers are eligible for in-place refresh by `trabuco sync`:
// the contents between the markers are owned by Trabuco and replaced on
// every sync run; everything outside the markers is user content and
// never touched.
//
// This is the only sync path that modifies an existing file. All other
// targets are additive (write-if-missing).
const (
	managedBlockBegin = "# === Trabuco-managed (regenerated by `trabuco sync`) ==="
	managedBlockEnd   = "# === End Trabuco-managed ==="
)

// detectLineEnding returns "\r\n" if content uses CRLF endings, else
// "\n". A file is considered CRLF if it contains at least one "\r\n"
// pair AND no bare LF lines exist that aren't part of one (i.e., the
// majority of newlines are CRLF). For our purposes — gitignore-style
// short config files — the simple heuristic of "any CRLF present"
// catches Windows-edited files cleanly without fighting mixed inputs.
func detectLineEnding(content string) string {
	if strings.Contains(content, "\r\n") {
		return "\r\n"
	}
	return "\n"
}

// extractManagedBlock returns the body of the Trabuco-managed block from
// content (the lines strictly between the begin and end markers). If
// either marker is missing or the markers appear in the wrong order,
// returns an empty string. Markers themselves are not included in the
// returned body.
//
// The returned body is normalized to LF line endings so callers can
// compare against an LF-rendered splice without false drift. CRLF
// preservation happens at apply time, where applyManagedBlock looks at
// the existing project file to decide which line ending to emit.
//
// Used during planning to read the expected block out of the
// generator-output file, and during apply to identify the block that
// needs replacing in the project file.
func extractManagedBlock(content string) string {
	beginIdx := strings.Index(content, managedBlockBegin)
	if beginIdx < 0 {
		return ""
	}
	// Skip past the begin marker and any trailing newline (\r\n or \n).
	bodyStart := beginIdx + len(managedBlockBegin)
	if bodyStart < len(content) && content[bodyStart] == '\r' {
		bodyStart++
	}
	if bodyStart < len(content) && content[bodyStart] == '\n' {
		bodyStart++
	}
	endIdx := strings.Index(content[bodyStart:], managedBlockEnd)
	if endIdx < 0 {
		return ""
	}
	body := content[bodyStart : bodyStart+endIdx]
	// Normalize CRLF body to LF for stable comparison.
	return strings.ReplaceAll(body, "\r\n", "\n")
}

// applyManagedBlock returns existing with the Trabuco-managed block
// replaced by expectedBody. If markers are present in existing, the
// content between them is replaced. If markers are absent, a fresh
// block (markers + body) is appended at the end of the file.
//
// expectedBody is the body of the block (no markers, LF-normalized). The
// rendered output uses the same line ending as existing (CRLF if existing
// is CRLF, else LF) so a Windows-edited file doesn't show as perpetual
// drift after splice.
//
// Defensive against partially-damaged files: if exactly one marker is
// found, the function ignores it and appends a fresh block — the user
// can clean up the dangling marker by hand. We never attempt heroic
// repairs on user-touched files.
func applyManagedBlock(existing, expectedBody string) string {
	nl := detectLineEnding(existing)

	// Normalize body to LF first (in case caller passed CRLF), then
	// retarget to whatever line ending the existing file uses.
	body := strings.ReplaceAll(expectedBody, "\r\n", "\n")
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	if nl != "\n" {
		body = strings.ReplaceAll(body, "\n", nl)
	}

	beginIdx := strings.Index(existing, managedBlockBegin)
	endMarkerIdx := strings.Index(existing, managedBlockEnd)

	if beginIdx >= 0 && endMarkerIdx > beginIdx {
		blockEnd := endMarkerIdx + len(managedBlockEnd)
		// Consume one trailing line-ending after the end marker so we
		// don't accumulate blank lines on each apply.
		if blockEnd < len(existing) && existing[blockEnd] == '\r' {
			blockEnd++
		}
		if blockEnd < len(existing) && existing[blockEnd] == '\n' {
			blockEnd++
		}
		replacement := managedBlockBegin + nl + body + managedBlockEnd + nl
		return existing[:beginIdx] + replacement + existing[blockEnd:]
	}

	// Markers absent or damaged. Append a fresh block at end.
	prefix := existing
	if prefix != "" && !strings.HasSuffix(prefix, nl) {
		prefix += nl
	}
	if prefix != "" && !strings.HasSuffix(prefix, nl+nl) {
		prefix += nl
	}
	return prefix + managedBlockBegin + nl + body + managedBlockEnd + nl
}
